#docker-compose.yml
version: "3.8"

services:
    php:
        build: ./docker/php
        volumes:
            - ./app:/var/www/symfony
        networks:
            - symfony

    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/symfony
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony

    db:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: secret
        networks:
            - symfony

networks:
    symfony:
